### ISSUE TITLE
cannot see all rooms

### ISSUE THREAD

**Issue by hunkydoryrepair** [colyseus/colyseus-monitor#27]
Unfortunately, the latest colyseus monitor doesn't allow us to find all the rooms.
It is limited to maybe a few hundred rooms that are displayed.  We have over 3000. Previously, we could find the long list.

All of the rooms are in the data. If we sort, we get different rooms displayed. But, since there is no search, we cannot find the rooms we need to find to kill or inspect.

**Comment by hunkydoryrepair** [comment]
Ok, found ability to search! So at least it is usable.

I think better if we could still paginate by removing these:
```      
hideFooter
hideFooterPagination
hideFooterSelectedRowCount
```

**Comment by endel** [comment]
Thank you for the report @hunkydoryrepair, just released a new version with your suggestion!

Unfortunately, the new "Material UI" update (https://github.com/colyseus/colyseus-monitor/pull/25) imposes a max of 100 rows under their MIT license (https://mui.com/x/react-data-grid/pagination/#size-of-the-page). If this becomes a big issue we can consider using something else instead of "Material UI"

**Comment by hunkydoryrepair** [comment]
thank you!
